global:
  resolve_timeout: 1m

route:
  receiver: "default-receiver"

receivers:
  - name: "default-receiver"
    webhook_configs:
      - url: "http://mimic-api:8000/alert"
        send_resolved: true
