# Dockerfile.train
FROM python:3.12-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos solo el código necesario para entrenar
COPY src/ /app/src/

# El comando no es un servidor web, es la ejecución lineal del pipeline
CMD ["sh", "-c", "python src/data_ingestion.py && python src/features.py && python src/train.py"]