version: '3.8'

services:
  train-manual:
    build:
      context: .
      dockerfile: Dockerfile.train
    container_name: trainer_manual
    # Sobrescribimos el CMD para ejecutar la versión manual
    command: ["sh", "-c", "python src/data_ingestion.py && python src/features.py && python src/train.py"]
    volumes:
      - ./models_output:/app/models
      - ./data_output:/app/data/processed
  api-manual:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api_manual
    ports:
      - "8000:8000"
    volumes:
      - ./models_output:/app/models
    environment:
      # Le indicamos que el modelo está en la ruta interna compartida
      - MODEL_PATH=/app/models/best_model.pkl